#!/bin/bash
alias ls=rm 0-alias 0x00-shell_basics 0x01-shell_permissions 0x03-shell_variables_expans 0x03-shell_variables_expansions 0x03-shell_variables_expansionsclear 0x03-shell_variables_expansionsecho README.md
